nelmio_cors:
    defaults:
        allow_origin: ['*']
        allow_credentials: false
        allow_headers: ['Content-Type', 'Authorization', 'X-User-Id', 'X-User-Role']
        allow_methods: ['GET', 'POST', 'PUT', 'PATCH', 'DELETE', 'OPTIONS']
        expose_headers: ['Content-Type']
        max_age: 3600
    paths:
        '^/':
            allow_origin: ['*']
            allow_credentials: false
